#!/usr/bin/bash
while IFS=$'\n' read -r unit
    do
        if [ -e "/$unit" ]
            then
                sed -i '/^User/d;/^Group/d' "/$unit"
                if grep -qo '^WorkingDirectory' "/$unit"
                    then mkdir -p "$(grep -m1 '^WorkingDirectory' "/$unit"|sed -E 's|.*=( )?|/|')"
                fi
        fi
done
